language: php

php:
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - php artisan migrate --force

before_install:
  - mysql -e 'create database staging;'

after_success:
  - curl https://forge.laravel.com/servers/49181/sites/103236/deploy/http?token=osUWms1fEU5pwOs5hG4jxle7FOGstksTzTjbu4zk