language: php

php:
  - 5.6
  - hhvm
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - php artisan migrate:refresh --seed

before_install:
  - mysql -e 'create database staging;'
